#pragma once
// Auto-generated InteractableSpawnCard paths from Unity assets
// Extracted 87 spawn cards using UnityPy
// Generated from Risk of Rain 2

#include <string>
#include <vector>

namespace InteractablePaths {
const std::vector<std::string> ALL_INTERACTABLE_PATHS = {
    "SpawnCards/InteractableSpawnCard/iscBarrel1",
    "SpawnCards/InteractableSpawnCard/iscBrokenDrone1",
    "SpawnCards/InteractableSpawnCard/iscBrokenDrone2",
    "SpawnCards/InteractableSpawnCard/iscBrokenEmergencyDrone",
    "SpawnCards/InteractableSpawnCard/iscBrokenEquipmentDrone",
    "SpawnCards/InteractableSpawnCard/iscBrokenFlameDrone",
    "SpawnCards/InteractableSpawnCard/iscBrokenMegaDrone",
    "SpawnCards/InteractableSpawnCard/iscBrokenMissileDrone",
    "SpawnCards/InteractableSpawnCard/iscBrokenTurret1",
    "SpawnCards/InteractableSpawnCard/iscCasinoChest",
    "SpawnCards/InteractableSpawnCard/iscCategoryChest2Damage",
    "SpawnCards/InteractableSpawnCard/iscCategoryChest2Healing",
    "SpawnCards/InteractableSpawnCard/iscCategoryChest2Utility",
    "SpawnCards/InteractableSpawnCard/iscCategoryChestDamage",
    "SpawnCards/InteractableSpawnCard/iscCategoryChestHealing",
    "SpawnCards/InteractableSpawnCard/iscCategoryChestUtility",
    "SpawnCards/InteractableSpawnCard/iscChest1",
    "SpawnCards/InteractableSpawnCard/iscChest1Stealthed",
    "SpawnCards/InteractableSpawnCard/iscChest2",
    "SpawnCards/InteractableSpawnCard/iscColossusPortal",
    "SpawnCards/InteractableSpawnCard/iscCommandChest",
    "SpawnCards/InteractableSpawnCard/iscDeepVoidPortal",
    "SpawnCards/InteractableSpawnCard/iscDeepVoidPortalBattery",
    "SpawnCards/InteractableSpawnCard/iscDestinationPortal",
    "SpawnCards/InteractableSpawnCard/iscDuplicator",
    "SpawnCards/InteractableSpawnCard/iscDuplicatorLarge",
    "SpawnCards/InteractableSpawnCard/iscDuplicatorMilitary",
    "SpawnCards/InteractableSpawnCard/iscDuplicatorWild",
    "SpawnCards/InteractableSpawnCard/iscEquipmentBarrel",
    "SpawnCards/InteractableSpawnCard/iscEventTrigger",
    "SpawnCards/InteractableSpawnCard/iscFreeChest",
    "SpawnCards/InteractableSpawnCard/iscGauntletEntrance",
    "SpawnCards/InteractableSpawnCard/iscGeode",
    "SpawnCards/InteractableSpawnCard/iscGoldChest",
    "SpawnCards/InteractableSpawnCard/iscGoldshoresBeacon",
    "SpawnCards/InteractableSpawnCard/iscGoldshoresPortal",
    "SpawnCards/InteractableSpawnCard/iscInfiniteTowerPortal",
    "SpawnCards/InteractableSpawnCard/iscInfiniteTowerSafeWard",
    "SpawnCards/InteractableSpawnCard/iscInfiniteTowerSafeWardAwaitingInteraction",
    "SpawnCards/InteractableSpawnCard/iscLemurianEgg",
    "SpawnCards/InteractableSpawnCard/iscLockbox",
    "SpawnCards/InteractableSpawnCard/iscLockboxVoid",
    "SpawnCards/InteractableSpawnCard/iscLunarChest",
    "SpawnCards/InteractableSpawnCard/iscLunarTeleporter",
    "SpawnCards/InteractableSpawnCard/iscMSPortal",
    "SpawnCards/InteractableSpawnCard/iscRadarTower",
    "SpawnCards/InteractableSpawnCard/iscScavBackpack",
    "SpawnCards/InteractableSpawnCard/iscScavLunarBackpack",
    "SpawnCards/InteractableSpawnCard/iscScrapper",
    "SpawnCards/InteractableSpawnCard/iscShopPortal",
    "SpawnCards/InteractableSpawnCard/iscShrineBlood",
    "SpawnCards/InteractableSpawnCard/iscShrineBloodSandy",
    "SpawnCards/InteractableSpawnCard/iscShrineBloodSnowy",
    "SpawnCards/InteractableSpawnCard/iscShrineBoss",
    "SpawnCards/InteractableSpawnCard/iscShrineBossSandy",
    "SpawnCards/InteractableSpawnCard/iscShrineBossSnowy",
    "SpawnCards/InteractableSpawnCard/iscShrineChance",
    "SpawnCards/InteractableSpawnCard/iscShrineChanceSandy",
    "SpawnCards/InteractableSpawnCard/iscShrineChanceSnowy",
    "SpawnCards/InteractableSpawnCard/iscShrineCleanse",
    "SpawnCards/InteractableSpawnCard/iscShrineCleanseSandy",
    "SpawnCards/InteractableSpawnCard/iscShrineCleanseSnowy",
    "SpawnCards/InteractableSpawnCard/iscShrineColossusAccess",
    "SpawnCards/InteractableSpawnCard/iscShrineCombat",
    "SpawnCards/InteractableSpawnCard/iscShrineCombatSandy",
    "SpawnCards/InteractableSpawnCard/iscShrineCombatSnowy",
    "SpawnCards/InteractableSpawnCard/iscShrineGoldshoresAccess",
    "SpawnCards/InteractableSpawnCard/iscShrineHalcyonite",
    "SpawnCards/InteractableSpawnCard/iscShrineHalcyoniteTier1",
    "SpawnCards/InteractableSpawnCard/iscShrineHealing",
    "SpawnCards/InteractableSpawnCard/iscShrineRestack",
    "SpawnCards/InteractableSpawnCard/iscShrineRestackSandy",
    "SpawnCards/InteractableSpawnCard/iscShrineRestackSnowy",
    "SpawnCards/InteractableSpawnCard/iscSquidTurret",
    "SpawnCards/InteractableSpawnCard/iscTeleporter",
    "SpawnCards/InteractableSpawnCard/iscTripleShop",
    "SpawnCards/InteractableSpawnCard/iscTripleShopEquipment",
    "SpawnCards/InteractableSpawnCard/iscTripleShopLarge",
    "SpawnCards/InteractableSpawnCard/iscVoidCamp",
    "SpawnCards/InteractableSpawnCard/iscVoidChest",
    "SpawnCards/InteractableSpawnCard/iscVoidChestSacrificeOn",
    "SpawnCards/InteractableSpawnCard/iscVoidCoinBarrel",
    "SpawnCards/InteractableSpawnCard/iscVoidOutroPortal",
    "SpawnCards/InteractableSpawnCard/iscVoidPortal",
    "SpawnCards/InteractableSpawnCard/iscVoidRaidSafeWard",
    "SpawnCards/InteractableSpawnCard/iscVoidSuppressor",
    "SpawnCards/InteractableSpawnCard/iscVoidTriple",
};
} // namespace InteractablePaths
