#pragma once
// Auto-generated InteractableSpawnCard addressable paths from lrapi_returns.json
// Extracted 87 addressable paths
// Generated from Risk of Rain 2

#include <string>
#include <unordered_map>

namespace InteractablePaths {

const std::unordered_map<std::string, std::string> ADDRESSABLE_PATHS = {
    {"iscBarrel1", "RoR2/Base/Barrel1/iscBarrel1.asset"},
    {"iscBrokenDrone1", "RoR2/Base/Drones/iscBrokenDrone1.asset"},
    {"iscBrokenDrone2", "RoR2/Base/Drones/iscBrokenDrone2.asset"},
    {"iscBrokenEmergencyDrone", "RoR2/Base/Drones/iscBrokenEmergencyDrone.asset"},
    {"iscBrokenEquipmentDrone", "RoR2/Base/Drones/iscBrokenEquipmentDrone.asset"},
    {"iscBrokenFlameDrone", "RoR2/Base/Drones/iscBrokenFlameDrone.asset"},
    {"iscBrokenMegaDrone", "RoR2/Base/Drones/iscBrokenMegaDrone.asset"},
    {"iscBrokenMissileDrone", "RoR2/Base/Drones/iscBrokenMissileDrone.asset"},
    {"iscBrokenTurret1", "RoR2/Base/Drones/iscBrokenTurret1.asset"},
    {"iscCasinoChest", "RoR2/Base/CasinoChest/iscCasinoChest.asset"},
    {"iscCategoryChest2Damage", "RoR2/DLC1/CategoryChest2/iscCategoryChest2Damage.asset"},
    {"iscCategoryChest2Healing", "RoR2/DLC1/CategoryChest2/iscCategoryChest2Healing.asset"},
    {"iscCategoryChest2Utility", "RoR2/DLC1/CategoryChest2/iscCategoryChest2Utility.asset"},
    {"iscCategoryChestDamage", "RoR2/Base/CategoryChest/iscCategoryChestDamage.asset"},
    {"iscCategoryChestHealing", "RoR2/Base/CategoryChest/iscCategoryChestHealing.asset"},
    {"iscCategoryChestUtility", "RoR2/Base/CategoryChest/iscCategoryChestUtility.asset"},
    {"iscChest1", "RoR2/Base/Chest1/iscChest1.asset"},
    {"iscChest1Stealthed", "RoR2/Base/Chest1StealthedVariant/iscChest1Stealthed.asset"},
    {"iscChest2", "RoR2/Base/Chest2/iscChest2.asset"},
    {"iscColossusPortal", "RoR2/DLC2/iscColossusPortal.asset"},
    {"iscCommandChest", "RoR2/CommandChest/iscCommandChest.asset"},
    {"iscDeepVoidPortal", "RoR2/DLC1/DeepVoidPortal/iscDeepVoidPortal.asset"},
    {"iscDeepVoidPortalBattery", "RoR2/DLC1/DeepVoidPortalBattery/iscDeepVoidPortalBattery.asset"},
    {"iscDestinationPortal", "RoR2/DLC2/iscDestinationPortal.asset"},
    {"iscDuplicator", "RoR2/Base/Duplicator/iscDuplicator.asset"},
    {"iscDuplicatorLarge", "RoR2/Base/DuplicatorLarge/iscDuplicatorLarge.asset"},
    {"iscDuplicatorMilitary", "RoR2/Base/DuplicatorMilitary/iscDuplicatorMilitary.asset"},
    {"iscDuplicatorWild", "RoR2/Base/DuplicatorWild/iscDuplicatorWild.asset"},
    {"iscEquipmentBarrel", "RoR2/Base/EquipmentBarrel/iscEquipmentBarrel.asset"},
    {"iscEventTrigger", "RoR2/DLC2/EventTrigger/iscEventTrigger.asset"},
    {"iscFreeChest", "RoR2/DLC1/FreeChest/iscFreeChest.asset"},
    {"iscGauntletEntrance", "RoR2/DLC1/gauntlets/iscGauntletEntrance.asset"},
    {"iscGeode", "RoR2/DLC2/iscGeode.asset"},
    {"iscGoldChest", "RoR2/Base/GoldChest/iscGoldChest.asset"},
    {"iscGoldshoresBeacon", "RoR2/Base/goldshores/iscGoldshoresBeacon.asset"},
    {"iscGoldshoresPortal", "RoR2/Base/PortalGoldshores/iscGoldshoresPortal.asset"},
    {"iscInfiniteTowerPortal", "RoR2/DLC1/GameModes/InfiniteTowerRun/InfiniteTowerAssets/iscInfiniteTowerPortal.asset"},
    {"iscInfiniteTowerSafeWard", "RoR2/DLC1/GameModes/InfiniteTowerRun/InfiniteTowerAssets/iscInfiniteTowerSafeWard.asset"},
    {"iscInfiniteTowerSafeWardAwaitingInteraction", "RoR2/DLC1/GameModes/InfiniteTowerRun/InfiniteTowerAssets/iscInfiniteTowerSafeWardAwaitingInteraction.asset"},
    {"iscLemurianEgg", "RoR2/CU8/LemurianEgg/iscLemurianEgg.asset"},
    {"iscLockbox", "RoR2/Junk/TreasureCache/iscLockbox.asset"},
    {"iscLockboxVoid", "RoR2/DLC1/TreasureCacheVoid/iscLockboxVoid.asset"},
    {"iscLunarChest", "RoR2/Base/LunarChest/iscLunarChest.asset"},
    {"iscLunarTeleporter", "RoR2/Base/Teleporters/iscLunarTeleporter.asset"},
    {"iscMSPortal", "RoR2/Base/PortalMS/iscMSPortal.asset"},
    {"iscRadarTower", "RoR2/Base/RadarTower/iscRadarTower.asset"},
    {"iscScavBackpack", "RoR2/Base/Scav/iscScavBackpack.asset"},
    {"iscScavLunarBackpack", "RoR2/Base/Scav/iscScavLunarBackpack.asset"},
    {"iscScrapper", "RoR2/Base/Scrapper/iscScrapper.asset"},
    {"iscShopPortal", "RoR2/Base/PortalShop/iscShopPortal.asset"},
    {"iscShrineBlood", "RoR2/Base/ShrineBlood/iscShrineBlood.asset"},
    {"iscShrineBloodSandy", "RoR2/Base/ShrineBlood/iscShrineBloodSandy.asset"},
    {"iscShrineBloodSnowy", "RoR2/Base/ShrineBlood/iscShrineBloodSnowy.asset"},
    {"iscShrineBoss", "RoR2/Base/ShrineBoss/iscShrineBoss.asset"},
    {"iscShrineBossSandy", "RoR2/Base/ShrineBoss/iscShrineBossSandy.asset"},
    {"iscShrineBossSnowy", "RoR2/Base/ShrineBoss/iscShrineBossSnowy.asset"},
    {"iscShrineChance", "RoR2/Base/ShrineChance/iscShrineChance.asset"},
    {"iscShrineChanceSandy", "RoR2/Base/ShrineChance/iscShrineChanceSandy.asset"},
    {"iscShrineChanceSnowy", "RoR2/Base/ShrineChance/iscShrineChanceSnowy.asset"},
    {"iscShrineCleanse", "RoR2/Base/ShrineCleanse/iscShrineCleanse.asset"},
    {"iscShrineCleanseSandy", "RoR2/Base/ShrineCleanse/iscShrineCleanseSandy.asset"},
    {"iscShrineCleanseSnowy", "RoR2/Base/ShrineCleanse/iscShrineCleanseSnowy.asset"},
    {"iscShrineColossusAccess", "RoR2/DLC2/iscShrineColossusAccess.asset"},
    {"iscShrineCombat", "RoR2/Base/ShrineCombat/iscShrineCombat.asset"},
    {"iscShrineCombatSandy", "RoR2/Base/ShrineCombat/iscShrineCombatSandy.asset"},
    {"iscShrineCombatSnowy", "RoR2/Base/ShrineCombat/iscShrineCombatSnowy.asset"},
    {"iscShrineGoldshoresAccess", "RoR2/Base/ShrineGoldshoresAccess/iscShrineGoldshoresAccess.asset"},
    {"iscShrineHalcyonite", "RoR2/DLC2/iscShrineHalcyonite.asset"},
    {"iscShrineHalcyoniteTier1", "RoR2/DLC2/iscShrineHalcyoniteTier1.asset"},
    {"iscShrineHealing", "RoR2/Base/ShrineHealing/iscShrineHealing.asset"},
    {"iscShrineRestack", "RoR2/Base/ShrineRestack/iscShrineRestack.asset"},
    {"iscShrineRestackSandy", "RoR2/Base/ShrineRestack/iscShrineRestackSandy.asset"},
    {"iscShrineRestackSnowy", "RoR2/Base/ShrineRestack/iscShrineRestackSnowy.asset"},
    {"iscSquidTurret", "RoR2/Junk/SquidTurret/iscSquidTurret.asset"},
    {"iscTeleporter", "RoR2/Base/Teleporters/iscTeleporter.asset"},
    {"iscTripleShop", "RoR2/Base/TripleShop/iscTripleShop.asset"},
    {"iscTripleShopEquipment", "RoR2/Base/TripleShopEquipment/iscTripleShopEquipment.asset"},
    {"iscTripleShopLarge", "RoR2/Base/TripleShopLarge/iscTripleShopLarge.asset"},
    {"iscVoidCamp", "RoR2/DLC1/VoidCamp/iscVoidCamp.asset"},
    {"iscVoidChest", "RoR2/DLC1/VoidChest/iscVoidChest.asset"},
    {"iscVoidChestSacrificeOn", "RoR2/DLC1/VoidChest/iscVoidChestSacrificeOn.asset"},
    {"iscVoidCoinBarrel", "RoR2/DLC1/VoidCoinBarrel/iscVoidCoinBarrel.asset"},
    {"iscVoidOutroPortal", "RoR2/DLC1/VoidOutroPortal/iscVoidOutroPortal.asset"},
    {"iscVoidPortal", "RoR2/DLC1/PortalVoid/iscVoidPortal.asset"},
    {"iscVoidRaidSafeWard", "RoR2/DLC1/VoidRaidCrab/iscVoidRaidSafeWard.asset"},
    {"iscVoidSuppressor", "RoR2/DLC1/VoidSuppressor/iscVoidSuppressor.asset"},
    {"iscVoidTriple", "RoR2/DLC1/VoidTriple/iscVoidTriple.asset"},
};

} // namespace InteractablePaths
