#pragma once
// Auto-generated InteractableSpawnCard addressable paths from lrapi_returns.json
// Extracted 87 addressable paths
// Generated from Risk of Rain 2

#include <string>
#include <unordered_map>

namespace InteractablePaths {

const std::unordered_map<std::string, std::string> INTERACTABLES = {
    {"3D Printer", "RoR2/Base/Duplicator/iscDuplicator.asset"},
    {"3D Printer (Green)", "RoR2/Base/DuplicatorLarge/iscDuplicatorLarge.asset"},
    {"Adaptive Chest", "RoR2/Base/CasinoChest/iscCasinoChest.asset"},
    {"Altar of Gold", "RoR2/Base/ShrineGoldshoresAccess/iscShrineGoldshoresAccess.asset"},
    {"Assessment Focus", "RoR2/DLC1/GameModes/InfiniteTowerRun/InfiniteTowerAssets/iscInfiniteTowerSafeWard.asset"},
    {"Assessment Focus (Awaiting)", "RoR2/DLC1/GameModes/InfiniteTowerRun/InfiniteTowerAssets/iscInfiniteTowerSafeWardAwaitingInteraction.asset"},
    {"Aurelionite Geode", "RoR2/DLC2/iscGeode.asset"},
    {"Barrel", "RoR2/Base/Barrel1/iscBarrel1.asset"},
    {"Blue Portal", "RoR2/Base/PortalShop/iscShopPortal.asset"},
    {"Broken Emergency Drone", "RoR2/Base/Drones/iscBrokenEmergencyDrone.asset"},
    {"Broken Equipment Drone", "RoR2/Base/Drones/iscBrokenEquipmentDrone.asset"},
    {"Broken Gunner Drone", "RoR2/Base/Drones/iscBrokenDrone1.asset"},
    {"Broken Gunner Turret", "RoR2/Base/Drones/iscBrokenTurret1.asset"},
    {"Broken Healing Drone", "RoR2/Base/Drones/iscBrokenDrone2.asset"},
    {"Broken Incinerator Drone", "RoR2/Base/Drones/iscBrokenFlameDrone.asset"},
    {"Broken Missile Drone", "RoR2/Base/Drones/iscBrokenMissileDrone.asset"},
    {"Broken TC-280", "RoR2/Base/Drones/iscBrokenMegaDrone.asset"},
    {"Celestial Portal", "RoR2/Base/PortalMS/iscMSPortal.asset"},
    {"Cell Vent", "RoR2/DLC1/VoidRaidCrab/iscVoidRaidSafeWard.asset"},
    {"Chest", "RoR2/Base/Chest1/iscChest1.asset"},
    {"Chest - Damage", "RoR2/Base/CategoryChest/iscCategoryChestDamage.asset"},
    {"Chest - Healing", "RoR2/Base/CategoryChest/iscCategoryChestHealing.asset"},
    {"Chest - Utility", "RoR2/Base/CategoryChest/iscCategoryChestUtility.asset"},
    {"Cleansing Pool", "RoR2/Base/ShrineCleanse/iscShrineCleanse.asset"},
    {"Cleansing Pool (Sandy)", "RoR2/Base/ShrineCleanse/iscShrineCleanseSandy.asset"},
    {"Cleansing Pool (Snowy)", "RoR2/Base/ShrineCleanse/iscShrineCleanseSnowy.asset"},
    {"Cloaked Chest", "RoR2/Base/Chest1StealthedVariant/iscChest1Stealthed.asset"},
    {"Command Chest", "RoR2/CommandChest/iscCommandChest.asset"},
    {"Crashed Multishop Terminal", "RoR2/DLC1/FreeChest/iscFreeChest.asset"},
    {"Deep Void Portal", "RoR2/DLC1/DeepVoidPortal/iscDeepVoidPortal.asset"},
    {"Deep Void Signal", "RoR2/DLC1/DeepVoidPortalBattery/iscDeepVoidPortalBattery.asset"},
    {"Destination Portal", "RoR2/DLC2/iscDestinationPortal.asset"},
    {"Encrusted Lockbox", "RoR2/DLC1/TreasureCacheVoid/iscLockboxVoid.asset"},
    {"Equipment Barrel", "RoR2/Base/EquipmentBarrel/iscEquipmentBarrel.asset"},
    {"Gauntlet Entrance", "RoR2/DLC1/gauntlets/iscGauntletEntrance.asset"},
    {"Gold Portal", "RoR2/Base/PortalGoldshores/iscGoldshoresPortal.asset"},
    {"Green Portal", "RoR2/DLC2/iscColossusPortal.asset"},
    {"Halcyon Beacon", "RoR2/Base/goldshores/iscGoldshoresBeacon.asset"},
    {"Halcyon Shrine", "RoR2/DLC2/iscShrineHalcyonite.asset"},
    {"Halcyon Shrine Tier 1", "RoR2/DLC2/iscShrineHalcyoniteTier1.asset"},
    {"Infinite Portal", "RoR2/DLC1/GameModes/InfiniteTowerRun/InfiniteTowerAssets/iscInfiniteTowerPortal.asset"},
    {"Large Chest", "RoR2/Base/Chest2/iscChest2.asset"},
    {"Large Chest - Damage", "RoR2/DLC1/CategoryChest2/iscCategoryChest2Damage.asset"},
    {"Large Chest - Healing", "RoR2/DLC1/CategoryChest2/iscCategoryChest2Healing.asset"},
    {"Large Chest - Utility", "RoR2/DLC1/CategoryChest2/iscCategoryChest2Utility.asset"},
    {"Legendary Chest", "RoR2/Base/GoldChest/iscGoldChest.asset"},
    {"Lemurian Egg", "RoR2/CU8/LemurianEgg/iscLemurianEgg.asset"},
    {"Lunar Pod", "RoR2/Base/LunarChest/iscLunarChest.asset"},
    {"Mili-Tech Printer", "RoR2/Base/DuplicatorMilitary/iscDuplicatorMilitary.asset"},
    {"Multishop Terminal", "RoR2/Base/TripleShop/iscTripleShop.asset"},
    {"Multishop Terminal (Equipment)", "RoR2/Base/TripleShopEquipment/iscTripleShopEquipment.asset"},
    {"Multishop Terminal (Green)", "RoR2/Base/TripleShopLarge/iscTripleShopLarge.asset"},
    {"Overgrown 3D Printer", "RoR2/Base/DuplicatorWild/iscDuplicatorWild.asset"},
    {"Prime Meridian - Event Trigger", "RoR2/DLC2/EventTrigger/iscEventTrigger.asset"},
    {"Radio Scanner", "RoR2/Base/RadarTower/iscRadarTower.asset"},
    {"Rusty Lockbox", "RoR2/Junk/TreasureCache/iscLockbox.asset"},
    {"Scavenger Backpack (Lunar)", "RoR2/Base/Scav/iscScavLunarBackpack.asset"},
    {"Scavenger's Sack", "RoR2/Base/Scav/iscScavBackpack.asset"},
    {"Scrapper", "RoR2/Base/Scrapper/iscScrapper.asset"},
    {"Shrine of Blood", "RoR2/Base/ShrineBlood/iscShrineBlood.asset"},
    {"Shrine of Blood (Sandy)", "RoR2/Base/ShrineBlood/iscShrineBloodSandy.asset"},
    {"Shrine of Blood (Snowy)", "RoR2/Base/ShrineBlood/iscShrineBloodSnowy.asset"},
    {"Shrine of Chance", "RoR2/Base/ShrineChance/iscShrineChance.asset"},
    {"Shrine of Chance (Sandy)", "RoR2/Base/ShrineChance/iscShrineChanceSandy.asset"},
    {"Shrine of Chance (Snowy)", "RoR2/Base/ShrineChance/iscShrineChanceSnowy.asset"},
    {"Shrine of Combat", "RoR2/Base/ShrineCombat/iscShrineCombat.asset"},
    {"Shrine of Combat (Sandy)", "RoR2/Base/ShrineCombat/iscShrineCombatSandy.asset"},
    {"Shrine of Combat (Snowy)", "RoR2/Base/ShrineCombat/iscShrineCombatSnowy.asset"},
    {"Shrine of Order", "RoR2/Base/ShrineRestack/iscShrineRestack.asset"},
    {"Shrine of Order (Sandy)", "RoR2/Base/ShrineRestack/iscShrineRestackSandy.asset"},
    {"Shrine of Order (Snowy)", "RoR2/Base/ShrineRestack/iscShrineRestackSnowy.asset"},
    {"Shrine of Shaping", "RoR2/DLC2/iscShrineColossusAccess.asset"},
    {"Shrine of the Mountain", "RoR2/Base/ShrineBoss/iscShrineBoss.asset"},
    {"Shrine of the Mountain (Sandy)", "RoR2/Base/ShrineBoss/iscShrineBossSandy.asset"},
    {"Shrine of the Mountain (Snowy)", "RoR2/Base/ShrineBoss/iscShrineBossSnowy.asset"},
    {"Shrine of the Woods", "RoR2/Base/ShrineHealing/iscShrineHealing.asset"},
    {"Squid Turret", "RoR2/Junk/SquidTurret/iscSquidTurret.asset"},
    {"Stalk", "RoR2/DLC1/VoidCoinBarrel/iscVoidCoinBarrel.asset"},
    {"Teleporter", "RoR2/Base/Teleporters/iscTeleporter.asset"},
    {"Teleporter (Lunar)", "RoR2/Base/Teleporters/iscLunarTeleporter.asset"},
    {"Void Cradle", "RoR2/DLC1/VoidChest/iscVoidChest.asset"},
    {"Void Cradle (Sacrifice)", "RoR2/DLC1/VoidChest/iscVoidChestSacrificeOn.asset"},
    {"Void Eradicator", "RoR2/DLC1/VoidSuppressor/iscVoidSuppressor.asset"},
    {"Void Outro Portal", "RoR2/DLC1/VoidOutroPortal/iscVoidOutroPortal.asset"},
    {"Void Portal", "RoR2/DLC1/PortalVoid/iscVoidPortal.asset"},
    {"Void Potential", "RoR2/DLC1/VoidTriple/iscVoidTriple.asset"},
    {"Void Seed", "RoR2/DLC1/VoidCamp/iscVoidCamp.asset"},
};

} // namespace InteractablePaths
